### PR TITLE
Dynamically update copyright year.

### LINKED ISSUE #80: Footer - Copyright year is hardcoded
Thank you for taking the time to file a Bug report.

**Describe the bug**
The current code uses statically typed copyright year "2021 Code is science", which requires updating the year manually every year.
Instead, the year could be dynamically updated using JavaScript's `Date` object.
**To Reproduce**

1. Go to Homepage or any page
3. Scroll down to Footer
4. Inspect the footer, you can observe that the year is hardcoded

**Expected behavior**
The copyright year should be updated automatically to the current running year.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 99.0.4844.84

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by prajwalkulkarni**
# Pull Request Template

## Description

Using the `Date` object's `getFullYear` method, the copyright year is updated automatically and eliminates the need to update it manually every year.

Fixes #80 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue).
- [x] New feature (non-breaking change which adds functionality).

## How Has This Been Tested?

Manual testing was performed on Chrome and Internet Edge to verify the functionality of added change and that the expected behavior matches the actual behavior.

## Additional Context (Please include any Screenshots/gifs if relevant)
footer

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.

### CODE REVIEW

File: src/components/Footer.js [hunk 1]
```diff
@@ -51,7 +51,7 @@ function Footer() {
         </Col>
       </Row>
       <Row className='footer-below'>
-        <p>2021 Code is Science</p>
+        <p>{new Date().getFullYear()}<sup>©</sup> Code is Science</p>
```
Comment (padmajabhol) [inline src/components/Footer.js]: Change it to : Copyright © {new Date().getFullYear()} Code is Science

Comment (prajwalkulkarni) [reply src/components/Footer.js]: I've updated it. Kindly review.

**Review by padmajabhol — APPROVED** [review]
